### ISSUE TITLE
client.cart.removeItem not working in Typescript Component

### ISSUE THREAD

**Issue by Cyklan** [MakairaIO/storefront-shop-adapter#61]
When using the function `client.cart.removeItem()` from `useShopClient` hook, it requires the `product` prop to be present. However, `product`s type is `never`. There are no legal values for never, which means that typescript won't compile the component.

Please update the type definition so that `product` is optional and of type never.

**Comment by JanMaeg** [comment]
@Cyklan The bug should be fixed in version `1.0.1` of `makaira@storefront-shop-adapter-shopify`-

https://github.com/MakairaIO/storefront-shop-adapter/releases/tag/%40makaira%2Fstorefront-shop-adapter-shopify-v1.0.1
